# **Задание 1**

In [3]:
import numpy as np
import random

variant = 17

## Общие параметры


In [188]:
sales = []

for i in range(4):
    sales.append([random.randint(variant, variant+100) for j in range(100000)])

print(sales) # 1-ая строка => 'автомобиль HAVAL', 2-ая => 'обувь', 3-ья => 'одежда', 4-ая => 'телефоны'

[[93, 56, 22, 96, 34, 17, 67, 53, 53, 113, 26, 35, 70, 73, 104, 33, 18, 70, 38, 104, 29, 114, 49, 85, 84, 43, 66, 82, 114, 51, 68, 73, 47, 23, 57, 94, 65, 32, 30, 19, 95, 71, 104, 67, 27, 21, 84, 74, 113, 72, 58, 117, 116, 20, 46, 108, 40, 92, 32, 52, 78, 85, 61, 38, 17, 76, 38, 20, 28, 102, 55, 109, 41, 101, 85, 84, 85, 67, 85, 60, 83, 46, 53, 117, 78, 28, 39, 91, 114, 111, 91, 29, 66, 21, 100, 82, 84, 83, 104, 48, 18, 57, 34, 21, 56, 97, 66, 106, 71, 23, 55, 19, 30, 67, 23, 83, 79, 60, 57, 104, 51, 89, 47, 60, 94, 72, 83, 25, 29, 91, 29, 67, 100, 61, 17, 57, 78, 83, 52, 43, 88, 59, 29, 93, 98, 18, 54, 34, 52, 86, 38, 101, 81, 88, 83, 88, 87, 66, 26, 104, 112, 41, 59, 108, 97, 40, 74, 21, 96, 75, 33, 114, 30, 100, 102, 41, 114, 57, 46, 77, 68, 36, 112, 22, 104, 22, 54, 32, 45, 76, 20, 29, 33, 68, 88, 41, 100, 96, 48, 51, 89, 19, 52, 91, 53, 36, 58, 33, 35, 108, 117, 26, 20, 17, 96, 48, 91, 76, 51, 117, 28, 18, 108, 72, 113, 97, 42, 89, 80, 31, 43, 115, 33, 19, 37, 35, 35, 66, 41, 77, 

## Решение через Python

In [189]:
products = ['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны']
prices = [20000, 3000, 45600, 5000]

revenue_py = []

In [190]:
def revenue_from_sales_py(arr):
    revenue = []
    
    for i in range(4):
        number_sales_product = 0
        for j in range(100000):
            number_sales_product += arr[i][j]
        revenue.append(number_sales_product * prices[i])
        
    return revenue

In [191]:
%timeit revenue_py = revenue_from_sales_py(sales)
# время работы кода на python

20.3 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [192]:
revenue_py = revenue_from_sales_py(sales)
for i in range(4):
    print(f"{products[i]}: ", end="")
    print("{:,}".format(revenue_py[i]))  

автомобиль HAVAL: 134,135,920,000
обувь: 20,063,259,000
одежда: 305,246,673,600
телефоны: 33,465,605,000


## Решение через NumPy

In [193]:
products = np.array(['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'])
prices = np.array([20000, 3000, 45600, 5000])
sales = np.array(sales)

revenue_sales_np = []

In [194]:
def revenue_from_sales_np(arr):
    revenue = []
    
    for i in range(4):
        number_sales_product = np.sum(sales[i])
        revenue.append(number_sales_product * prices[i])
        
    return revenue

In [195]:
%timeit revenue_np = revenue_from_sales_np(sales)
# время работы кода на numpy

79.6 µs ± 1.67 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [196]:
revenue_np = revenue_from_sales_np(sales)
for i in range(4):
    print(f"{products[i]}: ", end="")
    print("{:,}".format(revenue_np[i]))  

автомобиль HAVAL: 134,135,920,000
обувь: 20,063,259,000
одежда: 305,246,673,600
телефоны: 33,465,605,000


## Решение через Numpy с использованием векторизации

In [197]:
products = np.array(['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'])
prices = np.array([20000, 3000, 45600, 5000])
sales = np.array(sales)

revenue_sales_np_vec = []

In [198]:
def revenue_from_sales_np_vec(arr):
    number_sales_product = np.sum(sales, axis = 1) * prices
    #revenue = number_sales_product * prices[i]
        
    return number_sales_product

In [199]:
%timeit revenue_np_vec = revenue_from_sales_np_vec(sales)
# время работы кода на numpy с использованием векторизации


66.2 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [200]:
revenue_np_vec = revenue_from_sales_np_vec(sales)
for i in range(4):
    print(f"{products[i]}: ", end="")
    print("{:,}".format(revenue_np[i]))

автомобиль HAVAL: 134,135,920,000
обувь: 20,063,259,000
одежда: 305,246,673,600
телефоны: 33,465,605,000


## Сравнение


In [201]:
print("Python = ", end="")
%timeit revenue_py = revenue_from_sales_py(sales)
# время работы кода на python

print("NumPy = ", end="")
%timeit revenue_np = revenue_from_sales_np(sales)
# время работы кода на numpy

print("NumPy vec = ", end="")
%timeit revenue_np_vec = revenue_from_sales_np_vec(sales)
# время работы кода на numpy с использованием векторизации

Python = 94.8 ms ± 3.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
NumPy = 78.9 µs ± 635 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
NumPy vec = 63.1 µs ± 928 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [202]:
x = np.arange(4)
new = np.vstack([x,revenue_py])
sorted_array = np.sort(revenue_py)

print("Вывод категорий товаров по возрастанию дохода: \n")
for ar in sorted_array:
    for i in range(4):
        if ar == new[1][i]:
            print(f"{products[i]}: ", end="")
            print("{:,}".format(new[1][i]))

Вывод категорий товаров по возрастанию дохода: 

обувь: 20,063,259,000
телефоны: 33,465,605,000
автомобиль HAVAL: 134,135,920,000
одежда: 305,246,673,600


# **Задание 2**

## Реализация heapsort

In [309]:
def heap_with_maxi_root(arr, i, max_index): # Пишем алгоритм по созданию двоичного дерева, в корне которого будет максимальный элемент
    
    node = i # Индекс текущего узелка
    l = 2 * i + 1 # Левый дочерний узел двоичного дерева у элемента с индексом i
    r = 2 * i + 2 # Правый дочерний узел
    
    
    # Посмотрим, существует ли левый дочерний узел у текущего элемента
    # и проверим, будет ли он больше по величене, чем текущий элемент
    if l < max_index and arr[node] < arr[l]:
        node = l # Сдвигаем наш указатель дальше
   

    # Аналогично с правым дочерним узлом
    if r < max_index and arr[node] < arr[r]:
        node = r # Сдвигаем наш указатель дальше
        
        
    # Если указатель не на текущем элементе, т.е. если среди дочерних элементов нашелся такой, который больше по значению, чем текущий, то свапаем их    
    if node != i: 
        arr[i], arr[node] = arr[node], arr[i]
        
        # Пока условие выполняется, т.е. данный кусочек дерева (который ниже i) неотсортирован, продолжаем его выстраивать под концепцию двоичного дерева с бОльшими родительскими узлами
        heap_with_maxi_root(arr, node, max_index)

        
        
def heap_sort(arr):
    
    max_index = len(arr)
 
    # Выстраиваем дерево с максимальной вершиной
    for i in range(max_index//2 - 1, -1, -1):
        heap_with_maxi_root(arr, i, max_index)
 
    # "Вырезаем" вершину отсортированного дерева и свапаем последний элемент списка(из тех, что еще неотсортированы) с вершиной
    for i in range(max_index - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i] 
        heap_with_maxi_root(arr, 0, i) # Заново сортируем после swap
        

In [310]:
array = np.random.randint(100, size = variant * 100).astype(int)
print(array)

[55 21 26 ... 50 60 53]


In [311]:
%%timeit
heap_sort(array)

12.1 ms ± 298 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [312]:
# Отсортированный массив
print(f"length = {len(array)}")
print(array)


length = 1700
[ 0  0  0 ... 99 99 99]


## Реализация heapsort на Python

In [313]:
array_2 = [random.randint(0, variant+100) for i in range(variant*100)]
print(array_2)

[19, 76, 2, 6, 20, 22, 101, 100, 13, 35, 62, 42, 51, 18, 111, 103, 116, 22, 12, 71, 84, 79, 62, 2, 83, 42, 37, 26, 77, 71, 102, 89, 21, 60, 33, 68, 53, 2, 100, 89, 36, 70, 10, 51, 112, 93, 66, 80, 27, 2, 6, 39, 27, 22, 63, 46, 16, 115, 6, 30, 43, 20, 83, 98, 21, 58, 21, 80, 3, 33, 39, 43, 0, 60, 29, 28, 48, 31, 45, 100, 111, 64, 55, 54, 16, 4, 61, 62, 90, 8, 30, 80, 108, 43, 107, 51, 101, 13, 107, 41, 3, 98, 89, 12, 67, 84, 72, 94, 64, 71, 39, 10, 8, 45, 117, 14, 45, 99, 37, 12, 54, 27, 101, 15, 68, 108, 88, 88, 20, 53, 102, 27, 73, 89, 49, 43, 12, 7, 92, 14, 101, 42, 0, 62, 33, 13, 26, 86, 49, 18, 59, 50, 7, 15, 66, 67, 41, 89, 5, 112, 46, 38, 107, 80, 46, 64, 88, 87, 65, 7, 38, 6, 11, 62, 32, 28, 82, 54, 0, 1, 99, 105, 62, 45, 57, 57, 7, 29, 105, 66, 43, 43, 18, 73, 103, 60, 5, 32, 15, 4, 31, 110, 6, 66, 93, 88, 43, 67, 108, 95, 112, 6, 48, 10, 56, 28, 83, 96, 117, 23, 59, 100, 51, 6, 67, 59, 5, 38, 72, 46, 5, 60, 5, 23, 88, 57, 115, 4, 94, 80, 13, 105, 39, 116, 92, 35, 67, 19, 46, 8

In [314]:
def max_heapify(arr,n,i):
    l = 2 * i + 1
    r = 2 * i + 2
 
    if l < n and arr[l] > arr[i]:
        largest = l
    else:
        largest = i
 
    if r < n and arr[r] > arr[largest]:
        largest = r
 
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        max_heapify(arr, n, largest)


def build_heap(arr):
    n = len(arr)
 
    for i in range(n, -1,-1):
        max_heapify(arr, n, i)
 
    for i in range(n-1,0,-1):
        arr[0] ,arr[i] = arr[i], arr[0]
        max_heapify(arr, i, 0)

In [315]:
%%timeit
build_heap(array_2)

3.4 ms ± 60.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [316]:
# Отсортированный массив
print(f"length = {len(array_2)}")
print(array_2)

length = 1700
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20

## np.sort()

In [317]:
array_3 = np.random.randint(100, size = variant * 100).astype(int)
print(array_3)

[21 42  8 ... 54 22 86]


In [318]:
%%timeit
np.sort(array_3)

39.8 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [319]:
# Отсортированный массив
print(f"length = {len(array_3)}")
print(np.sort(array_3))

length = 1700
[ 0  0  0 ... 99 99 99]


## Сравнение времени

In [320]:
print("My_heapsort = ", end="") 
%timeit heap_sort(array)

print("Python = ", end="") 
%timeit build_heap(array_2)

print("Np.sort() = ", end="") 
%timeit np.sort(array_3)

My_heapsort = 12.2 ms ± 239 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Python = 3.28 ms ± 66 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Np.sort() = 39.3 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# **Задание 3**

In [4]:
data = np.genfromtxt('/Users/dmitry/Downloads/drinks.csv', delimiter=',', skip_header = 1, 
                     dtype={ 
                            "names": ["country", "beer_servings", "spirit_servings", "wine_servings", "total_litres_of_pure_alcohol"],
                            "formats": ["U20", "i4", "i4", "i4", "f8"]
                            }
                    )  

In [5]:
print(data[:20])

[('Afghanistan',   0,   0,   0,  0. ) ('Albania',  89, 132,  54,  4.9)
 ('Algeria',  25,   0,  14,  0.7) ('Andorra', 245, 138, 312, 12.4)
 ('Angola', 217,  57,  45,  5.9)
 ('Antigua & Barbuda', 102, 128,  45,  4.9)
 ('Argentina', 193,  25, 221,  8.3) ('Armenia',  21, 179,  11,  3.8)
 ('Australia', 261,  72, 212, 10.4) ('Austria', 279,  75, 191,  9.7)
 ('Azerbaijan',  21,  46,   5,  1.3) ('Bahamas', 122, 176,  51,  6.3)
 ('Bahrain',  42,  63,   7,  2. ) ('Bangladesh',   0,   0,   0,  0. )
 ('Barbados', 143, 173,  36,  6.3) ('Belarus', 142, 373,  42, 14.4)
 ('Belgium', 295,  84, 212, 10.5) ('Belize', 263, 114,   8,  6.8)
 ('Benin',  34,   4,  13,  1.1) ('Bhutan',  23,   0,   0,  0.4)]


In [28]:
beer_max = data["country"][np.argmax(data['beer_servings'])]
print(f"Первое место в списке потребителей пива: {beer_max} -> {np.max(data['beer_servings'])}")

spirit_max = data["country"][np.argmax(data['spirit_servings'])]
print(f"Первое место в списке потребителей крепких спиртных напитков: {spirit_max} -> {np.max(data['spirit_servings'])}")

wine_max = data["country"][np.argmax(data['wine_servings'])]
print(f"Первое место в списке потребителей вина: {wine_max} -> {np.max(data['wine_servings'])}")

alcohol_max = data["country"][np.argmax(data['total_litres_of_pure_alcohol'])]
print(f"Первое место в списке потребителей алкоголя: {alcohol_max} -> {np.max(data['total_litres_of_pure_alcohol'])}")


Первое место в списке потребителей пива: Namibia -> 376
Первое место в списке потребителей крепких спиртных напитков: Grenada -> 438
Первое место в списке потребителей вина: France -> 370
Первое место в списке потребителей алкоголя: Belarus -> 14.4


# **Задание 4**