# **Задание 1**

In [18]:
import numpy as np
import random

variant = 17

In [19]:
sales = []

for i in range(4):
    sales.append([random.randint(variant, variant+100) for j in range(100000)])

for i in range(4):
    print(sales[i][:20]) # 1-ая строка => 'автомобиль HAVAL', 2-ая => 'обувь', 3-ья => 'одежда', 4-ая => 'телефоны'

[61, 48, 55, 37, 37, 45, 84, 85, 64, 58, 63, 72, 52, 18, 43, 43, 41, 46, 105, 92]
[98, 90, 62, 81, 71, 116, 116, 110, 94, 71, 90, 69, 112, 61, 53, 72, 71, 95, 24, 37]
[98, 68, 54, 85, 107, 40, 101, 23, 51, 46, 116, 110, 112, 18, 83, 92, 60, 88, 71, 76]
[36, 96, 28, 24, 58, 82, 31, 65, 44, 85, 39, 107, 51, 20, 102, 94, 114, 26, 86, 74]


## Общие параметры


## Решение через Python

In [20]:
products = ['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны']
prices = [20000, 3000, 45600, 5000]

revenue_py = []

In [21]:
def revenue_from_sales_py(arr):
    revenue = []
    
    for i in range(4):
        number_sales_product = 0
        for j in range(100000):
            number_sales_product += arr[i][j]
        revenue.append(number_sales_product * prices[i])
        
    return revenue

In [22]:
%timeit revenue_py = revenue_from_sales_py(sales)
# время работы кода на python

20.3 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
revenue_py = revenue_from_sales_py(sales)
for i in range(4):
    print(f"{products[i]}: ", end="")
    print("{:,}".format(revenue_py[i]))  

автомобиль HAVAL: 134,300,440,000
обувь: 20,131,320,000
одежда: 305,600,438,400
телефоны: 33,480,445,000


## Решение через NumPy

In [24]:
products = np.array(['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'])
prices = np.array([20000, 3000, 45600, 5000])
sales = np.array(sales)

revenue_sales_np = []

In [25]:
def revenue_from_sales_np(arr):
    revenue = []
    
    for i in range(4):
        number_sales_product = np.sum(sales[i])
        revenue.append(number_sales_product * prices[i])
        
    return revenue

In [26]:
%timeit revenue_np = revenue_from_sales_np(sales)
# время работы кода на numpy

79.1 µs ± 1 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [27]:
revenue_np = revenue_from_sales_np(sales)
for i in range(4):
    print(f"{products[i]}: ", end="")
    print("{:,}".format(revenue_np[i]))  

автомобиль HAVAL: 134,300,440,000
обувь: 20,131,320,000
одежда: 305,600,438,400
телефоны: 33,480,445,000


## Решение через Numpy с использованием векторизации

In [28]:
products = np.array(['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'])
prices = np.array([20000, 3000, 45600, 5000])
sales = np.array(sales)

revenue_sales_np_vec = []

In [29]:
def revenue_from_sales_np_vec(arr):
    number_sales_product = np.sum(sales, axis = 1) * prices
    #revenue = number_sales_product * prices[i]
        
    return number_sales_product

In [30]:
%timeit revenue_np_vec = revenue_from_sales_np_vec(sales)
# время работы кода на numpy с использованием векторизации


63.5 µs ± 1.31 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
revenue_np_vec = revenue_from_sales_np_vec(sales)
for i in range(4):
    print(f"{products[i]}: ", end="")
    print("{:,}".format(revenue_np[i]))

автомобиль HAVAL: 134,300,440,000
обувь: 20,131,320,000
одежда: 305,600,438,400
телефоны: 33,480,445,000


## Сравнение


In [32]:
print("Python = ", end="")
%timeit revenue_py = revenue_from_sales_py(sales)
# время работы кода на python

print("NumPy = ", end="")
%timeit revenue_np = revenue_from_sales_np(sales)
# время работы кода на numpy

print("NumPy vec = ", end="")
%timeit revenue_np_vec = revenue_from_sales_np_vec(sales)
# время работы кода на numpy с использованием векторизации

Python = 94.9 ms ± 1.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
NumPy = 76.5 µs ± 713 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
NumPy vec = 65 µs ± 987 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [33]:
x = np.arange(4)
new = np.vstack([x,revenue_py])
sorted_array = np.sort(revenue_py)

print("Вывод категорий товаров по возрастанию дохода: \n")
for ar in sorted_array:
    for i in range(4):
        if ar == new[1][i]:
            print(f"{products[i]}: ", end="")
            print("{:,}".format(new[1][i]))

Вывод категорий товаров по возрастанию дохода: 

обувь: 20,131,320,000
телефоны: 33,480,445,000
автомобиль HAVAL: 134,300,440,000
одежда: 305,600,438,400


# **Задание 2**

## Реализация heapsort

In [34]:
def heap_with_maxi_root(arr, i, max_index): # Пишем алгоритм по созданию двоичного дерева, в корне которого будет максимальный элемент
    
    node = i # Индекс текущего узелка
    l = 2 * i + 1 # Левый дочерний узел двоичного дерева у элемента с индексом i
    r = 2 * i + 2 # Правый дочерний узел
    
    
    # Посмотрим, существует ли левый дочерний узел у текущего элемента
    # и проверим, будет ли он больше по величене, чем текущий элемент
    if l < max_index and arr[node] < arr[l]:
        node = l # Сдвигаем наш указатель дальше
   

    # Аналогично с правым дочерним узлом
    if r < max_index and arr[node] < arr[r]:
        node = r # Сдвигаем наш указатель дальше
        
        
    # Если указатель не на текущем элементе, т.е. если среди дочерних элементов нашелся такой, который больше по значению, чем текущий, то свапаем их    
    if node != i: 
        arr[i], arr[node] = arr[node], arr[i]
        
        # Пока условие выполняется, т.е. данный кусочек дерева (который ниже i) неотсортирован, продолжаем его выстраивать под концепцию двоичного дерева с бОльшими родительскими узлами
        heap_with_maxi_root(arr, node, max_index)

        
        
def heap_sort(arr):
    
    max_index = len(arr)
 
    # Выстраиваем дерево с максимальной вершиной
    for i in range(max_index//2 - 1, -1, -1):
        heap_with_maxi_root(arr, i, max_index)
 
    # "Вырезаем" вершину отсортированного дерева и свапаем последний элемент списка(из тех, что еще неотсортированы) с вершиной
    for i in range(max_index - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i] 
        heap_with_maxi_root(arr, 0, i) # Заново сортируем после swap
        

In [35]:
array = np.random.randint(100, size = variant * 100).astype(int)
print(array)

[50 84 59 ... 33 60 75]


In [36]:
%%timeit
heap_sort(array)

11.9 ms ± 307 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
# Отсортированный массив
print(f"length = {len(array)}")
print(array)


length = 1700
[ 0  0  0 ... 99 99 99]


## Реализация heapsort на Python

In [39]:
array_2 = [random.randint(0, variant+100) for i in range(variant*100)]
print(array_2[:20])

[46, 21, 94, 13, 1, 107, 5, 108, 22, 98, 32, 19, 58, 91, 101, 98, 39, 7, 29, 68]


In [40]:
def max_heapify(arr,n,i):
    l = 2 * i + 1
    r = 2 * i + 2
 
    if l < n and arr[l] > arr[i]:
        largest = l
    else:
        largest = i
 
    if r < n and arr[r] > arr[largest]:
        largest = r
 
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        max_heapify(arr, n, largest)


def build_heap(arr):
    n = len(arr)
 
    for i in range(n, -1,-1):
        max_heapify(arr, n, i)
 
    for i in range(n-1,0,-1):
        arr[0] ,arr[i] = arr[i], arr[0]
        max_heapify(arr, i, 0)

In [41]:
%%timeit
build_heap(array_2)

3.32 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
# Отсортированный массив
print(f"length = {len(array_2)}")
print(array_2[:100])

length = 1700
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6]


## np.sort()

In [44]:
array_3 = np.random.randint(100, size = variant * 100).astype(int)
print(array_3)

[48 45 11 ... 18 53 19]


In [45]:
%%timeit
np.sort(array_3)

39.6 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [46]:
# Отсортированный массив
print(f"length = {len(array_3)}")
print(np.sort(array_3))

length = 1700
[ 0  0  0 ... 99 99 99]


## Сравнение времени

In [47]:
print("My_heapsort = ", end="") 
%timeit heap_sort(array)

print("Python = ", end="") 
%timeit build_heap(array_2)

print("Np.sort() = ", end="") 
%timeit np.sort(array_3)

My_heapsort = 12.2 ms ± 224 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Python = 3.46 ms ± 59.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Np.sort() = 40.8 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# **Задание 3**

In [48]:
data = np.genfromtxt('/Users/dmitry/Downloads/drinks.csv', delimiter=',', skip_header = 1, 
                     dtype={ 
                            "names": ["country", "beer_servings", "spirit_servings", "wine_servings", "total_litres_of_pure_alcohol"],
                            "formats": ["U20", "i4", "i4", "i4", "f8"]
                            }
                    )  

In [49]:
alc_data = np.genfromtxt('/Users/dmitry/Downloads/drinks.csv', delimiter=',', skip_header = 1, dtype = [('country', 'U20'), ('beer_servings', 'i4'),
('spirit_servings', 'i4'), ('wine_servings', 'i4'), ('total_litres_of_pure_alcohol', 'f8')])

In [50]:
data

array([('Afghanistan',   0,   0,   0,  0. ),
       ('Albania',  89, 132,  54,  4.9), ('Algeria',  25,   0,  14,  0.7),
       ('Andorra', 245, 138, 312, 12.4), ('Angola', 217,  57,  45,  5.9),
       ('Antigua & Barbuda', 102, 128,  45,  4.9),
       ('Argentina', 193,  25, 221,  8.3),
       ('Armenia',  21, 179,  11,  3.8),
       ('Australia', 261,  72, 212, 10.4),
       ('Austria', 279,  75, 191,  9.7),
       ('Azerbaijan',  21,  46,   5,  1.3),
       ('Bahamas', 122, 176,  51,  6.3), ('Bahrain',  42,  63,   7,  2. ),
       ('Bangladesh',   0,   0,   0,  0. ),
       ('Barbados', 143, 173,  36,  6.3),
       ('Belarus', 142, 373,  42, 14.4), ('Belgium', 295,  84, 212, 10.5),
       ('Belize', 263, 114,   8,  6.8), ('Benin',  34,   4,  13,  1.1),
       ('Bhutan',  23,   0,   0,  0.4), ('Bolivia', 167,  41,   8,  3.8),
       ('Bosnia-Herzegovina',  76, 173,   8,  4.6),
       ('Botswana', 173,  35,  35,  5.4), ('Brazil', 245, 145,  16,  7.2),
       ('Brunei',  31,   2,   1,  

In [ ]:
print(alc_data['country'])